# SQlite3 database setup
# $Id$

production:
#  adapter: sqlite3
#  dbfile: db/production.db
#mysql:
  adapter: mysql
  database: redmine
  host: localhost
  username: redmine
  password: redmine
  encoding: utf8

#
#pgsql:
#  adapter: postgresql
#  database: redmine
#  host: localhost
#  username: postgres
#  password: "postgres"
